// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgFST4E7f_GnjV0TGtaiTsOVwyu93WtyQ',
    appId: '1:701664435254:web:74ab4f3c5a226cbc5a0c97',
    messagingSenderId: '701664435254',
    projectId: 'gearshop-45fd1',
    authDomain: 'gearshop-45fd1.firebaseapp.com',
    storageBucket: 'gearshop-45fd1.firebasestorage.app',
    measurementId: 'G-SC94XJNJYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSs6jmdSE4vk6ZwSNi5dIuYKjWR69pMnE',
    appId: '1:701664435254:android:b0ba0471aefc8e825a0c97',
    messagingSenderId: '701664435254',
    projectId: 'gearshop-45fd1',
    storageBucket: 'gearshop-45fd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAoO1At7n07f3kwiLhI74XjjwuCm3QMVU',
    appId: '1:701664435254:ios:4d24b243846f10835a0c97',
    messagingSenderId: '701664435254',
    projectId: 'gearshop-45fd1',
    storageBucket: 'gearshop-45fd1.firebasestorage.app',
    androidClientId: '701664435254-c2dnq97nkk4bnrkefdh3bo0fuub0llm4.apps.googleusercontent.com',
    iosClientId: '701664435254-o8b7l1url0vutr9ii85ijtm5692ond9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.gearapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgFST4E7f_GnjV0TGtaiTsOVwyu93WtyQ',
    appId: '1:701664435254:web:4dc7f327ee61acd35a0c97',
    messagingSenderId: '701664435254',
    projectId: 'gearshop-45fd1',
    authDomain: 'gearshop-45fd1.firebaseapp.com',
    storageBucket: 'gearshop-45fd1.firebasestorage.app',
    measurementId: 'G-6EL1E9GZCF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAoO1At7n07f3kwiLhI74XjjwuCm3QMVU',
    appId: '1:701664435254:ios:4d24b243846f10835a0c97',
    messagingSenderId: '701664435254',
    projectId: 'gearshop-45fd1',
    storageBucket: 'gearshop-45fd1.firebasestorage.app',
    androidClientId: '701664435254-c2dnq97nkk4bnrkefdh3bo0fuub0llm4.apps.googleusercontent.com',
    iosClientId: '701664435254-o8b7l1url0vutr9ii85ijtm5692ond9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.gearapp',
  );

}